# Generated by Django 4.1.7 on 2023-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastbooking',
            name='reservation_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
